/* Generated by Convex. To regenerate: npx convex dev */
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const server_1 = require("convex/server");
exports.api = server_1.anyApi;
exports.internal = server_1.anyApi;
