/* Generated by Convex. To regenerate: npx convex dev */
import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as catalog from "../catalog";

declare const fullApi: ApiFromModules<{
  catalog: typeof catalog;
}>;

export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
