/* Generated by Convex. To regenerate: npx convex dev */
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const server_1 = require("convex/server");
exports.query = server_1.queryGeneric;
exports.internalQuery = server_1.internalQueryGeneric;
exports.mutation = server_1.mutationGeneric;
exports.internalMutation = server_1.internalMutationGeneric;
exports.action = server_1.actionGeneric;
exports.internalAction = server_1.internalActionGeneric;
exports.httpAction = server_1.httpActionGeneric;
