/**
 * Category slugs and titleKeys aligned with public/catalogCategoryRules.json.
 * Used for homepage cards, product pages, and sitemap.
 */
export const CATEGORY_SLUGS = [
  "gloves",
  "wkladki",
  "polbuty",
  "trzewiki",
  "sandaly",
  "klapki",
  "kalosze",
  "caps",
  "aprons",
  "sweatshirts",
  "koszula",
  "t-shirt",
  "jackets",
  "kurtki-softshell",
  "polar",
  "spodnie",
  "ogrodniczki",
  "spodnie-krotkie",
  "spodnie-ocieplane",
  "vests",
  "kamizelki-ocieplane",
  "odziez-gastronomiczna",
  "helmets",
  "eyewear",
  "earProtection",
  "masks",
  "kneeProtection",
  "rainwear",
  "firstAid",
  "signage",
  "reczniki",
  "other",
] as const;

export type CategorySlug = (typeof CATEGORY_SLUGS)[number];

export const CATEGORY_TITLE_KEYS: Record<CategorySlug, string> = {
  gloves: "productNames.gloves",
  wkladki: "productNames.wkladki",
  polbuty: "productNames.polbuty",
  trzewiki: "productNames.trzewiki",
  sandaly: "productNames.sandaly",
  klapki: "productNames.klapki",
  kalosze: "productNames.kalosze",
  caps: "productNames.caps",
  aprons: "productNames.aprons",
  sweatshirts: "productNames.sweatshirts",
  koszula: "productNames.koszula",
  "t-shirt": "productNames.tShirt",
  jackets: "productNames.jackets",
  "kurtki-softshell": "productNames.kurtkiSoftshell",
  polar: "productNames.polar",
  spodnie: "productNames.clothing",
  ogrodniczki: "productNames.ogrodniczki",
  "spodnie-krotkie": "productNames.spodnieKrotkie",
  "spodnie-ocieplane": "productNames.spodnieOcieplane",
  vests: "productNames.vests",
  "kamizelki-ocieplane": "productNames.kamizelkiOcieplane",
  "odziez-gastronomiczna": "productNames.odziezGastronomiczna",
  helmets: "productNames.helmets",
  eyewear: "productNames.eyewear",
  earProtection: "productNames.earProtection",
  masks: "productNames.masks",
  kneeProtection: "productNames.kneeProtection",
  rainwear: "productNames.rainwear",
  firstAid: "productNames.firstAid",
  signage: "productNames.signage",
  reczniki: "productNames.reczniki",
  other: "products.catalogOther",
};
