/**
 * Catalog category types. Category rules and data live in:
 *   - scripts/catalogCategoryRules.json (rules for split script)
 *   - src/data/catalog/*.json (generated by scripts/split-catalog-by-category.mjs)
 * Use @/data/catalog for getCatalogGroupedByCategory(), getCatalogBySlug(), getCategories().
 */

import type { KartotekaRow } from './kartoteki';

export type CatalogCategorySlug =
  | 'gloves'
  | 'polbuty'
  | 'trzewiki'
  | 'sandaly'
  | 'kalosze'
  | 'spodnie'
  | 'vests'
  | 'koszula'
  | 'helmets'
  | 'eyewear'
  | 'earProtection'
  | 'masks'
  | 'kneeProtection'
  | 'rainwear'
  | 'firstAid'
  | 'signage'
  | 'other';

/** Product row with optional image path (from catalogImages.json, keyed by Kod). */
export type CatalogProduct = KartotekaRow & { image?: string };

export type CatalogSection = {
  slug: CatalogCategorySlug;
  titleKey: string;
  items: CatalogProduct[];
};
